accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login', views.login_view, name='login'),
    path('register', views.register_view, name='register'),
    path('logout', views.logout_view, name='logout')
]

core/urls.py
from django.urls import path
from . import views
from django.contrib import admin

app_name = 'core'

admin.site.site_header = 'SuperGym'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('panel', views.panel, name='panel'),
    path('client/panel/', views.client_panel_view, name='client_panel'),
    path('client/panel/payments/checkout', views.checkout_view, name='checkout'),
    path('client/panel/payments', views.payments_view, name='payments'),
    path('client/panel/secrvices', views.services_view, name='services'),
    path('client/requests/service/add/<int:id>', views.add_service, name='add_service'),
    path('client/requests/service/checkout', views.checkout_pay, name='checkout_pay'),
    path('staff/panel/', views.staff_panel_view, name='staff_panel')
]

silka/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('account/', include('accounts.urls')),
    path('admin/', admin.site.urls)
]

urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login', views.login_view, name='login'),
    path('register', views.register_view, name='register'),
    path('logout', views.logout_view, name='logout')
]

accounts/models.py
from django.db import models

# Create your models here.

core/models.py
from email import message
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Service(models.Model):
    name = models.CharField(max_length=50)
    price = models.IntegerField()
    
    def __str__(self) -> str:
        return self.name



class UserService(models.Model):
    client = models.ForeignKey(User, on_delete=models.CASCADE)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)
    
    def __str__(self) -> str:
        return f"{self.client} -> {self.service} | {'aktywny' if self.active else 'nieaktywny'}"
    

class PaymentMethods(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self) -> str:
        return self.name


class Payments(models.Model):
    client = models.ForeignKey(User, on_delete=models.CASCADE)
    method = models.ForeignKey(PaymentMethods, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    to_pay = models.IntegerField()
    payed = models.IntegerField(default=0)
    realized = models.BooleanField(default=False)
    
    def __str__(self) -> str:
        return f"{self.date} | {self.client} zapłacił {self.payed} PLN"

class Messages(models.Model):
    employee = models.ForeignKey(User, on_delete=models.CASCADE, related_name='employee')
    client = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='client')
    message = models.TimeField(max_length=500)
    date = models.DateTimeField(auto_now_add=True)
    read = models.BooleanField()
    
    
class Statistics(models.Model):
    total_subsribers = models.BigIntegerField()
    total_clients = models.BigIntegerField()
    current_workout = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self) -> str:
        return self.date
    
class Visits(models.Model):
    entrace = models.DateTimeField(auto_now_add=True)
    exited = models.DateTimeField(blank=True)
    client = models.ForeignKey(User, on_delete=models.CASCADE)
    place = models.CharField(max_length=50)
    visits = models.IntegerField(default=0)

accounts/views.py
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, update_session_auth_hash
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.shortcuts import render, redirect




def login_view(request):
    if request.user.is_authenticated:
        return redirect('core:home')
        
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('core:panel')
    else:
        form = AuthenticationForm()
        
    context = {
        'title': "Zaloguj się",
        'form': form
    }
    return render(request, "accounts/login.html", context)


def register_view(request):
    if request.user.is_authenticated: 
        return redirect('core:panel')
    
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('core:panel')
    else:
        form = UserCreationForm()
        
    context = {
        'title': "Zarejestruj się",
        'form': form
    }
    return render(request, "accounts/register.html", context)


@login_required
def logout_view(request):
    if request.method == 'GET':
        logout(request)
        return redirect('core:home')

core/views.py
from django.shortcuts import redirect, render, HttpResponse
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model

from .models import PaymentMethods, Payments, Service, UserService

def home_view(request):
    return render(request, 'core/home.html')





def panel(request):
    '''Redirects to correct panel'''    
    if request.user.is_authenticated:
        if request.user.is_staff:
            return redirect('core:staff_panel')
        
        return redirect('core:client_panel')
    
    return redirect('core:home')
    

@staff_member_required
def staff_panel_view(request):
    User = get_user_model()
    users = User.objects.all()
    context = {
        'users': users
    }
    return render(request, 'core/staff_panel.html', context)

@login_required
def client_panel_view(request):
    context = {
        'user': request.user
    }
    return render(request, 'core/client_panel.html', context)


@login_required
def checkout_view(request):
    services = UserService.objects.filter(client=request.user, active=False)
    payments = PaymentMethods.objects.all()
    total = 0
    for s in services:
        total += s.service.price

    context = {
        'services': services,
        'total': total,
        'payments': payments
    }
    return render(request, 'core/checkout.html', context)

@login_required()
def checkout_pay(request):
    services = UserService.objects.filter(client=request.user, active=False)
    total = 0
    for s in services:
        total += s.service.price
    UserService.objects.filter(
        client=request.user).update(active=True)
    
    Payments.objects.create(
        client=request.user,
        method_id=3,
        to_pay = total,
        payed = total,
        realized = True
        
    )
    return redirect('core:payments')

@login_required
def payments_view(request):
    services = UserService.objects.filter(client=request.user, active=False)
    payments = Payments.objects.filter(client=request.user)
    total = 0
    for s in services:
        total += s.service.price

    context = {
        'services': services,
        'total': total,
        'payments': payments
    }
    return render(request, 'core/payments.html', context)

@login_required
def services_view(request):
    services = Service.objects.all()
    
    context = {
        'services': services
    }
    return render(request, 'core/services.html', context)

@login_required
def add_service(request, id):
    service = UserService.objects.create(client=request.user,service_id=id, active=False)
    return redirect('core:payments')
    

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}


{% block imports %}
<link rel="stylesheet" href="{% static 'css/auth.css' %}">
{% endblock imports %}


{% block content %}
<main>
    <h1 class="center-text">Zaloguj się</h1>
    <form method="post" class="auth-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="stretch btn btn-primary">Zaloguj</button>
    </form>
    
</main>
{% endblock content %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}


{% block imports %}
<link rel="stylesheet" href="{% static 'css/auth.css' %}">
{% endblock imports %}


{% block content %}
<main>
    <h1 class="center-text">Zarejestruj się</h1>
    <form method="post" class="auth-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="stretch btn btn-primary">Zarejestruj</button>
    </form>

</main>
{% endblock content %}

core/templates/base.html
{% load static %}
<!DOCTYPE ht ml>
<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap/bootstrap.bundle.js' %}"></script>
    <script src="https://kit.fontawesome.com/bee8d9d382.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block imports %}
    {% endblock imports %}
    <script src="{% static 'js/base.js' %}"></script>
    <title>SuperGym</title>
</head>

<body>
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark mb-5">
        <div class="container-xl">
            <a class="navbar-brand" href="{% url 'core:panel' %}">💪 SuperGym</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
                <div class="collapse navbar-collapse">
                    <ul class="navbar-nav ms-auto" >
                        {% if user.is_authenticated %}
                        
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:logout' %}">Wyloguj się</a>
                        </li>
                        
                        {% else %}
                        
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:register' %}">Dołącz</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:login' %}">Logowanie</a>
                        </li>
                        
                        {% endif %}
                        
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container-xl" id="main">
        {% block content %}
        

        {% endblock content %}
    </div>
    <div class="container">
        <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
            <div class="col-md-4 d-flex align-items-center">
                <a class="navbar-brand" href="{% url 'core:panel' %}">💪 SuperGym</a>
                <span class="text-muted">© 2022 SuperGym sp. z.o.o</span>
            </div>
    
            <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
                <li class="ms-3"><a class="text-muted" href="#"><i class="fa-brands fa-facebook" style="font-size: 25px;"></i></a></li>
                <li class="ms-3"><a class="text-muted" href="#"><i class="fa-brands fa-instagram" style="font-size: 25px;"></i></a></li>
                <li class="ms-3"><a class="text-muted" href="#"><i class="fa-brands fa-twitter" style="font-size: 25px;"></i></a></li>
            </ul>
        </footer>
    </div>
</body>

</html>

core/templates/core/checkout.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="row g-5">
    <div class="col-md-5 col-lg-4 order-md-last">
        <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-primary">Twój koszyk</span>
            <span class="badge bg-primary rounded-pill">3</span>
        </h4>
        <ul class="list-group mb-3">
            {% for s in services %}
            <li class="list-group-item d-flex justify-content-between lh-sm">
                <div>
                    <h6 class="my-0">{{ s.service.name }}</h6>
                    <small class="text-muted">Dodatkowa usługa</small>
                </div>
                <span class="text-muted">{{ s.service.price }} PLN</span>
            </li>
            {% endfor %}
            
            <li class="list-group-item d-flex justify-content-between">
                <span>Cena całkowita (PLN)</span>
                <strong>{{ total }} PLN</strong>
            </li>
        </ul>

        <form class="card p-2">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Promo code">
                <button type="submit" class="btn btn-secondary">Redeem</button>
            </div>
        </form>
    </div>
    <div class="col-md-7 col-lg-8">
        <form action="{% url 'core:checkout_pay' %}">
            <h4 class="mb-3">Payment</h4>

            <div class="my-3">
                {% for payment in payments %}
                <div class="form-check">
                    <input id="credit" name="paymentMethod" type="radio" class="form-check-input">
                    <label class="form-check-label" for="credit">{{ payment.name }}</label>
                </div>
                {% endfor %}
            </div>

            <div class="row gy-3">
                <div class="col-md-6">
                    <label for="cc-name" class="form-label">Name on card</label>
                    <input required required type="text" class="form-control" id="cc-name" placeholder="" required="">
                    <small class="text-muted">Full name as displayed on card</small>
                    <div class="invalid-feedback">
                        Name on card is required
                    </div>
                </div>

                <div class="col-md-6">
                    <label for="cc-number" class="form-label">Credit card number</label>
                    <input required type="text" class="form-control" id="cc-number" placeholder="" required="">
                    <div class="invalid-feedback">
                        Credit card number is required
                    </div>
                </div>

                <div class="col-md-3">
                    <label for="cc-expiration" class="form-label">Expiration</label>
                    <input required type="text" class="form-control" id="cc-expiration" placeholder="" required="">
                    <div class="invalid-feedback">
                        Expiration date required
                    </div>
                </div>

                <div class="col-md-3">
                    <label for="cc-cvv" class="form-label">CVV</label>
                    <input required type="text" class="form-control" id="cc-cvv" placeholder="" required="">
                    <div class="invalid-feedback">
                        Security code required
                    </div>
                </div>
            </div>

            <hr class="my-4">

            <button class="w-100 btn btn-primary btn-lg" type="submit">Kontynuuj</button>
        </form>
    </div>
</div>

{% endblock content %}

core/templates/core/client_panel.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="row">
    
{% include "core/partials/client_menu.html" %}   

<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4"><div class="chartjs-size-monitor" style="position: absolute; inset: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
    <h1 class="h2">Witaj {{ user }}!</h1>
    
    </div>

    <img src="{% static 'img/chart.png' %}" class="img-fluid">

    <h2>Twoje ostatnie wizyty</h2>
    <div class="table-responsive">
    <table class="table table-striped table-sm">
        <thead>
        <tr>
            <th>Numer wizyty</th>
            <th>Wejście</th>
            <th>Wyjście</th>
            <th>Miejsce</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        </tbody>
    </table>
    </div>
</main>
</div>
{% endblock content %}

core/templates/core/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1 class="heading">SuperGym to cos więcej niż siłownia</h1>
<p>Zaloguj się aby dostać się do panelu</p>
<img src="{% static 'img/header.webp' %}" alt="header" style="width: 100%">
<div class="container px-4 py-5" id="featured-3">
    <h2 class="pb-2 border-bottom">Dlaczego my?</h2>
    <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
        <div class="feature col">
            <i class="fa-solid fa-wallet hd"></i>
            <h2>Tanio</h2>
            <p>Paragraph of text beneath the heading to explain the heading. We'll add onto it with another sentence and
                probably just keep going until we run out of words.</p>
        </div>
        <div class="feature col">
            <i class="fa-solid fa-dumbbell hd"></i>
            <h2>Najnowszy sprzęt</h2>
            <p>Paragraph of text beneath the heading to explain the heading. We'll add onto it with another sentence and
                probably just keep going until we run out of words.</p>
        </div>
        <div class="feature col">
            <i class="fa-solid fa-clock hd"></i>
            <h2>Otwarte 24/7</h2>
            <p>Paragraph of text beneath the heading to explain the heading. We'll add onto it with another sentence and
                probably just keep going until we run out of words.</p>
        </div>
    </div>
    <div>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal">Cennik</h1>
            <p class="fs-5 text-muted">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quasi, perspiciatis repudiandae. Culpa rerum, reprehenderit id, qui tempora tempore minima, inventore repudiandae ullam porro in numquam dolore impedit nulla fuga? Corrupti!</p>
        </div>
        <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">Początkujący</h4>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">$3<small class="text-muted fw-light">/mo</small></h1>
                        <ul class="list-unstyled mt-3 mb-4">
                            <li>10 users included</li>
                            <li>2 GB of storage</li>
                            <li>Email support</li>
                            <li>Help center access</li>
                        </ul>
                        <button type="button" class="w-100 btn btn-lg btn-outline-primary">Dołącz</button>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">Początkujący</h4>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">$7<small class="text-muted fw-light">/mo</small></h1>
                        <ul class="list-unstyled mt-3 mb-4">
                            <li>20 users included</li>
                            <li>10 GB of storage</li>
                            <li>Priority email support</li>
                            <li>Help center access</li>
                        </ul>
                        <button type="button" class="w-100 btn btn-lg btn-outline-primary">Dołącz</button>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm border-primary">
                    <div class="card-header py-3 text-white bg-primary border-primary">
                        <h4 class="my-0 fw-normal">Zaawansowany</h4>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">$10<small class="text-muted fw-light">/mo</small></h1>
                        <ul class="list-unstyled mt-3 mb-4">
                            <li>30 users included</li>
                            <li>15 GB of storage</li>
                            <li>Phone and email support</li>
                            <li>Help center access</li>
                        </ul>
                        <button type="button" class="w-100 btn btn-lg btn-primary">Dołącz</button>
                    </div>
                </div>
            </div>
        </div>
    
        <h2 class="display-6 text-center mb-4">Różnice subskrypcji</h2>
    
        <div class="table-responsive">
            <table class="table text-center">
                <thead>
                    <tr>
                        <th style="width: 34%;"></th>
                        <th style="width: 22%;">Student</th>
                        <th style="width: 22%;">Początkujący</th>
                        <th style="width: 22%;">Zaawansowany</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row" class="text-start">Public</th>
                        <td><i class="fa-solid fa-check"></i></td>
                        <td><i class="fa-solid fa-check"></i></td>
                        <td><i class="fa-solid fa-check"></i></td>
                    </tr>
                    <tr>
                        <th scope="row" class="text-start">Private</th>
                        <td></td>
                        <td><i class="fa-solid fa-check"></i></td>
                        <td><i class="fa-solid fa-check"></i></td>
                    </tr>
                </tbody>
    
                <tbody>
                    <tr>
                        <th scope="row" class="text-start">Permissions</th>
                        <td><i class="fa-solid fa-check"></i></td>
                        <td><i class="fa-solid fa-check"></i></td>
                        <td><i class="fa-solid fa-check"></i></td>
                    </tr>
                    <tr>
                        <th scope="row" class="text-start">Sharing</th>
                        <td></td>
                        <td><i class="fa-solid fa-check"></i></td>
                        <td><i class="fa-solid fa-check"></i></td>
                    </tr>
                    <tr>
                        <th scope="row" class="text-start">Unlimited members</th>
                        <td></td>
                        <td><i class="fa-solid fa-check"></i></td>
                        <td><i class="fa-solid fa-check"></i></td>
                    </tr>
                    <tr>
                        <th scope="row" class="text-start">Extra security</th>
                        <td></td>
                        <td></td>
                        <td><i class="fa-solid fa-check"></i></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}

core/templates/core/partials/client_menu.html
 <nav class="col-md-2 d-none d-md-block sidebar">
    <div class="sidebar-sticky">
    <ul class="nav flex-column">
        <li class="nav-item">
        <a class="nav-link" href="{% url 'core:panel' %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
            Strona główna <span class="sr-only">(current)</span>
        </a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'core:payments' %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2 13 9 20 9"></polyline></svg>
            Płatności
        </a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'core:services' %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-cart"><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg>
            Usługi
        </a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="#">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
            Pomoc
        </a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="#">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-layers"><polygon points="12 2 2 7 12 12 22 7 12 2"></polygon><polyline points="2 17 12 22 22 17"></polyline><polyline points="2 12 12 17 22 12"></polyline></svg>
            Ustawienia
        </a>
        </li>
    </ul>
    </div>
</nav>

core/templates/core/payments.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="row">

{% include "core/partials/client_menu.html" %}    

<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4"><div class="chartjs-size-monitor" style="position: absolute; inset: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
    <h1 class="h2">Witaj {{ user }}!</h1>
    </div>
    <p> Do zapłaty masz: {{ total }} zł  </p>
    
    <a href="{% url 'core:checkout' %}"><button class="btn btn-primary">Zapłać</button></a>
        
    <hr class="my-4">
    <h2>Nieopłacone usługi</h2>
    <div class="table-responsive">
    <table class="table table-striped table-sm">
        <thead>
        <tr>
            <th>Usługa</th>
            <th>Koszt</th>
            
        </tr>
        </thead>
        <tbody>
            {% for s in services %}
        <tr>
            <td> {{ s.service.name }}</td>
            <td> {{ s.service.price }} </td>
                
            
        </tr>
            {% endfor  %}
        </tbody>
    </table>
    </div>


    <h2>Twoje płatności</h2>
    <div class="table-responsive">
    <table class="table table-striped table-sm">
        <thead>
        <tr>
            <th>Data</th>
            <th>Zapłacono</th>
            <th>Metoda</th>
            <th>Status</th>
        </tr>
        </thead>
        <tbody>
        {% for payment in payments %}
        <tr>
            <td>{{ payment.date }}</td>
            <td>{{ payment.payed }} PLN</td>
            <td>{{ payment.method }}</td>
            <td> Opłacone </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
</main>
</div>
{% endblock content %}

core/templates/core/services.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="row">

{% include "core/partials/client_menu.html" %}    

<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4"><div class="chartjs-size-monitor" style="position: absolute; inset: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
    <h1 class="h2">Witaj {{ user }}!</h1>
    </div>
    <h2>Usługi</h2>
    <div class="table-responsive">
    <table class="table table-striped table-sm">
        <thead>
        <tr>
            <th>Usługa</th>
            <th>Koszt</th>
            <th>Akcja</th>
            
        </tr>
        </thead>
        <tbody>
            {% for service in services %}
        <tr>
            <td> {{ service.name }}</td>
            <td> {{ service.price }} </td>
            <td>
                <a href="{% url 'core:add_service' id=service.id %}"> 
                    <button class="btn btn-success">Aktywuj</button>
                </a>
            </td>
                
            
        </tr>
            {% endfor  %}
        </tbody>
    </table>
    </div>
</main>
</div>
{% endblock content %}